Test the copy mechanism

diff --git a/.github/workflows/create-repo.yml b/.github/workflows/create-repo.yml
--- a/.github/workflows/create-repo.yml
+++ b/.github/workflows/create-repo.yml
@@ -3,13 +3,13 @@ name: Create and Populate Repo
 on:
   workflow_dispatch:
     inputs:
-      folder-path:
-        description: 'Path to the folder to copy over'
-        required: true
-        default: './'
       candidate:
         description: 'Candidate''s username to invite'
         required: true
+      folder-path:
+        description: 'Path to the folder to copy over'
+        required: true
+        default: 'v1'
 
 jobs:
   create-repo:
@@ -41,13 +41,19 @@ jobs:
           REPO_NAME="${{ steps.generate-name.outputs.repo-name }}"
           FOLDER_PATH="${{ github.event.inputs.folder-path }}"
           echo "Path to copy over: $FOLDER_PATH."
-          echo "Current Directory: $PWD"
-          ls -la $PWD
+          if [ ! -d "$FOLDER_PATH" ]; then
+            echo "Folder $FOLDER_PATH does not exist!"
+            exit 1
+          fi
           cd "$REPO_NAME"
-          echo "Current Directory: $PWD"
+          cp -r ../"$FOLDER_PATH"/* .
+          cp ../README.md . || echo "README.md not found, skipping"
+          cp ../.github/workflows/main.yml .github/workflows/main.yml || echo "Workflow main.yml not found, skipping"
+          cp ../.github/workflows/no-changes.txt .github/workflows/no-changes.txt || echo "Workflow no-changes.txt not found, skipping"
           ls -la $PWD
-          echo "Workflow Directory: $GITHUB_WORKSPACE"
-          ls -la $GITHUB_WORKSPACE
+          git add .
+          git commit -m "Initial commit"
+          git push -u origin main
 
       - name: Invite collaborator
         run: |
